# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "bento/centos-7.3"

Vagrant.configure("2") do |config|
  config.vm.define "consul-master-01" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "consul-master-01"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.71"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
  config.vm.define "consul-master-02" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "consul-master-02"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.72"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
config.vm.define "consul-master-03" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "consul-mastrt-03"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.73"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "  
  end
config.vm.define "deployer" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "deploy"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.70"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "  
  end
  config.vm.define "websrv-01" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "websrv-01"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.81"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
  config.vm.define "websrv-02" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "websrv-02"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.82"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
config.vm.define "websrv-03" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "consul-mastrt-03"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.83"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
config.vm.define "nginx" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "deploy"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.80"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
  config.vm.define "elastic-01" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "elastic-01"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.91"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
  config.vm.define "elastic-02" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "elastic-02"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.92"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end
config.vm.define "elastic-03" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "elastic-03"
    subconfig.vm.network "public_network", bridge: "eno1", ip: "10.0.0.93"
  config.vm.provision "shell",
    run: "always",
    inline: "ip route add default via 10.0.0.1 "
  end

# Install consul on all machines  
  config.vm.provision "shell", inline: <<-SHELL
   yum install -y deltarpm
   yum install -y yum-utils
   yum-config-manager --add-repo https://repo.saltstack.com/yum/redhat/7.3/x86_64/saltstack-rhel7.repo
   yum clean expire-cache
   yum install -y httpd
   yum install -y nginx
   yum install -y salt-minion
   useradd joey ; echo -e "xxxxxxxx\nxxxxxxx" | passwd joey
   yum -y install unzip wget
  SHELL
 end

